package com.apargo.service.auditlog.model;



import com.apargo.service.auditlog.enums.AuditActorType;
import com.apargo.service.auditlog.enums.AuditEventStatus;
import com.apargo.service.auditlog.enums.AuditEventType;
import com.apargo.service.auditlog.enums.Module;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.Map;

/**
 * Single centralized audit record for every module (template, messaging,
 * storage, wallet, users, projects, plans, waba ...).
 * <p>
 * Module-specific data (e.g. storageKey, batchTotalFiles, deleteType,
 * campaign recipient counts) does NOT get its own column/field here —
 * it goes into {@link #metadata}. This is the whole reason this service
 * runs on MongoDB rather than a fixed-column relational table: every
 * module has a different metadata shape, and a schemaless document lets
 * all of them share one collection without a migration every time a new
 * module or event type is added.
 * <p>
 * Write-heavy: this document is optimized for fast inserts. Read/query
 * concerns live in {@code repository.read} + {@code service.query}, kept
 * deliberately separate from the write path (see repository/write).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "audit_log")
@CompoundIndexes({
        @CompoundIndex(
                name = "idx_org_project_occurred",
                def = "{'orgId': 1, 'projectId': 1, 'occurredAt': -1}"
        ),
        @CompoundIndex(
                name = "idx_org_module_occurred",
                def = "{'orgId': 1, 'module': 1, 'occurredAt': -1}"
        ),
        @CompoundIndex(
                name = "idx_org_eventtype_occurred",
                def = "{'orgId': 1, 'eventType': 1, 'occurredAt': -1}"
        ),
        @CompoundIndex(
                name = "idx_actor_occurred",
                def = "{'actorId': 1, 'occurredAt': -1}"
        ),
        @CompoundIndex(
                name = "idx_entity",
                def = "{'entityType': 1, 'entityId': 1, 'occurredAt': -1}"
        ),
        @CompoundIndex(
                name = "idx_status_occurred",
                def = "{'eventStatus': 1, 'occurredAt': -1}"
        )
})
public class AuditLog {

    // ── Identity ─────────────────────────────────────────────────────────────

    @Id
    private String id;

    /**
     * Idempotency key supplied by the producing service (or generated by
     * IdempotencyUtil for Kafka messages missing one). Unique so retried
     * Kafka deliveries / REST retries never create a duplicate audit row.
     */
    @Indexed(unique = true)
    private String eventId;

    // ── Classification ───────────────────────────────────────────────────────

    private Module module;

    private AuditEventType eventType;

    private AuditEventStatus eventStatus;

    // ── Who / Where ──────────────────────────────────────────────────────────

    private Long orgId;

    private Long projectId; // nullable — org-level events

    private AuditActorType actorType;

    private Long actorId; // nullable for SYSTEM / SCHEDULER / WORKER events

    private String ipAddress; // nullable

    private String userAgent; // nullable

    // ── What ─────────────────────────────────────────────────────────────────

    /** Logical resource type this event acted on, e.g. TEMPLATE, CAMPAIGN, FILE. */
    private String entityType;

    /**
     * Resource identifier. String rather than Long because entity ids vary
     * across modules (numeric ids, storage keys, UUIDs, etc.).
     */
    private String entityId;

    // ── Correlation ──────────────────────────────────────────────────────────

    private String requestId; // nullable — ties back to originating HTTP request

    private String traceId; // nullable — ties together a chain of events

    // ── Change detail (optional, only when relevant) ────────────────────────

    private Map<String, Object> oldValue; // nullable, null on *_CREATED events

    private Map<String, Object> newValue; // nullable, null on *_DELETED events

    /**
     * Module-specific payload. Everything that used to be a dedicated column
     * per module (storageKey, fileSizeBytes, batchTotalFiles, deleteType,
     * recipientCount, quotaLevel, etc.) lives here as free-form key/value data.
     */
    @Builder.Default
    private Map<String, Object> metadata = Map.of();

    private String errorMessage; // nullable, populated when eventStatus == FAILURE

    // ── Timestamps ───────────────────────────────────────────────────────────

    /** When the event actually happened at the source service (client-supplied). */
    private Instant occurredAt;

    /**
     * When this service persisted the record. Always server-generated —
     * never trust occurredAt alone for ordering/compliance since it is
     * client-supplied and could be skewed or backdated.
     */
    private Instant recordedAt;
}
