spring:
  application:
    name: auditlog

  profiles:
    include:
      - dev
      # - kafka

  mongodb:
    uri: mongodb+srv://root:ashishmongo123@cluster0.sw3tj.mongodb.net/audit

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auditlog-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: MANUAL

messaging:
  audit:
    topics:
      campaign: whatsapp.campaign.audit.events
      conversation: whatsapp.conversation.audit.events
      dispatch: whatsapp.dispatch.audit.events