spring:
  application:
    name: auditlog

  profiles:
    include:
      - dev
      - kafka

  data:
    mongodb:
      uri: mongodb+srv://root:ashishmongo123@cluster0.sw3tj.mongodb.net/audit
      database: audit



springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized


eureka:
  client:
    service-url:
      defaultZone: http://146.88.24.113:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true